package fusion.um.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 20 16:15:31 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FuncApprovals_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FuncApprovals_VOImpl() {
    }
}
