package fusion.um.model.AM.common;

import java.util.ArrayList;

import java.util.Map;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 25 18:39:29 IST 2018
// ---------------------------------------------------------------------
public interface Functions_AM extends ApplicationModule {
    ArrayList getLOVValues(String tableName, String value, String displayValue,
                           String lookupType);

    Map applicationSessionSetup();
}
