package fusion.um.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 26 11:19:22 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuAccess_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MenuAccess_VOImpl() {
    }

    /**
     * Returns the variable value for BV_ROLE_ID.
     * @return variable value for BV_ROLE_ID
     */
    public String getBV_ROLE_ID() {
        return (String)ensureVariableManager().getVariableValue("BV_ROLE_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_ROLE_ID.
     * @param value value to bind as BV_ROLE_ID
     */
    public void setBV_ROLE_ID(String value) {
        ensureVariableManager().setVariableValue("BV_ROLE_ID", value);
    }
}
