package fusion.um.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 25 18:24:13 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataGroupDetail_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DataGroupDetail_VOImpl() {
    }
}
