package fusion.um.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 21 00:51:03 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FuncChecklist_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FuncChecklist_VOImpl() {
    }
}
