package fusion.um.model.VO;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 20 14:24:19 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FuncApprLevels_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ApprLevelId {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getApprLevelId();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setApprLevelId((Number)value);
            }
        }
        ,
        FuncId {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setFuncId((Number)value);
            }
        }
        ,
        LevelNo {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLevelNo();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLevelNo((Number)value);
            }
        }
        ,
        LevelName {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLevelName();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLevelName((String)value);
            }
        }
        ,
        LevelType {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLevelType();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLevelType((String)value);
            }
        }
        ,
        ApprByAll {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getApprByAll();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setApprByAll((String)value);
            }
        }
        ,
        ActiveYn {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        Trans_Active {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getTrans_Active();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setTrans_Active((Boolean)value);
            }
        }
        ,
        Trans_Active_2 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getTrans_Active_2();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setTrans_Active_2((Boolean)value);
            }
        }
        ,
        FuncApprovals_VO {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getFuncApprovals_VO();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Level_Type_STATVO1 {
            public Object get(FuncApprLevels_VORowImpl obj) {
                return obj.getLevel_Type_STATVO1();
            }

            public void put(FuncApprLevels_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FuncApprLevels_VORowImpl object);

        public abstract void put(FuncApprLevels_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPRLEVELID = AttributesEnum.ApprLevelId.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int LEVELNO = AttributesEnum.LevelNo.index();
    public static final int LEVELNAME = AttributesEnum.LevelName.index();
    public static final int LEVELTYPE = AttributesEnum.LevelType.index();
    public static final int APPRBYALL = AttributesEnum.ApprByAll.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int TRANS_ACTIVE = AttributesEnum.Trans_Active.index();
    public static final int TRANS_ACTIVE_2 = AttributesEnum.Trans_Active_2.index();
    public static final int FUNCAPPROVALS_VO = AttributesEnum.FuncApprovals_VO.index();
    public static final int LEVEL_TYPE_STATVO1 = AttributesEnum.Level_Type_STATVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FuncApprLevels_VORowImpl() {
    }

    /**
     * Gets FuncApprLevels_EO entity object.
     * @return the FuncApprLevels_EO
     */
    public EntityImpl getFuncApprLevels_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for APPR_LEVEL_ID using the alias name ApprLevelId.
     * @return the APPR_LEVEL_ID
     */
    public Number getApprLevelId() {
        return (Number) getAttributeInternal(APPRLEVELID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_LEVEL_ID using the alias name ApprLevelId.
     * @param value value to set the APPR_LEVEL_ID
     */
    public void setApprLevelId(Number value) {
        setAttributeInternal(APPRLEVELID, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public Number getFuncId() {
        return (Number) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(Number value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for LEVEL_NO using the alias name LevelNo.
     * @return the LEVEL_NO
     */
    public Number getLevelNo() {
        return (Number) getAttributeInternal(LEVELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LEVEL_NO using the alias name LevelNo.
     * @param value value to set the LEVEL_NO
     */
    public void setLevelNo(Number value) {
        setAttributeInternal(LEVELNO, value);
    }

    /**
     * Gets the attribute value for LEVEL_NAME using the alias name LevelName.
     * @return the LEVEL_NAME
     */
    public String getLevelName() {
        return (String) getAttributeInternal(LEVELNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LEVEL_NAME using the alias name LevelName.
     * @param value value to set the LEVEL_NAME
     */
    public void setLevelName(String value) {
        setAttributeInternal(LEVELNAME, value);
    }

    /**
     * Gets the attribute value for LEVEL_TYPE using the alias name LevelType.
     * @return the LEVEL_TYPE
     */
    public String getLevelType() {
        return (String) getAttributeInternal(LEVELTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LEVEL_TYPE using the alias name LevelType.
     * @param value value to set the LEVEL_TYPE
     */
    public void setLevelType(String value) {
        setAttributeInternal(LEVELTYPE, value);
    }

    /**
     * Gets the attribute value for APPR_BY_ALL using the alias name ApprByAll.
     * @return the APPR_BY_ALL
     */
    public String getApprByAll() {
        return (String) getAttributeInternal(APPRBYALL);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_BY_ALL using the alias name ApprByAll.
     * @param value value to set the APPR_BY_ALL
     */
    public void setApprByAll(String value) {
        setAttributeInternal(APPRBYALL, value);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Active.
     * @return the Trans_Active
     */
     public Boolean getTrans_Active() {
         Boolean flag = false;
         if (this.getActiveYn() != null && this.getActiveYn().equals("Y")) {
             flag = true;
//             System.err.println("flag"  + flag);
         } else {
             flag = false;
//             System.err.println("flag"  + flag);
         }
         return flag;
//          return (Boolean) getAttributeInternal(TRANS_ACTIVE);
     }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Active.
     * @param value value to set the  Trans_Active
     */
     public void setTrans_Active(Boolean value) {
         if (value) {
             setActiveYn("Y");
         } else {
             setActiveYn("N");
         }
         setAttributeInternal(TRANS_ACTIVE, value);
     }


    /**
     * Gets the attribute value for the calculated attribute Trans_Active_2.
     * @return the Trans_Active_2
     */
     public Boolean getTrans_Active_2() {
         Boolean flag = false;
         if (this.getApprByAll() != null && this.getApprByAll().equals("Y")) {
             flag = true;
//             System.err.println("flag"  + flag);
         } else {
             flag = false;
//             System.err.println("flag"  + flag);
         }
         return flag;
     //         return (Boolean) getAttributeInternal(TRANS_ACTIVE_2);
     }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Active_2.
     * @param value value to set the  Trans_Active_2
     */
     public void setTrans_Active_2(Boolean value) {
         if (value) {
             setApprByAll("Y");
         } else {
             setApprByAll("N");
         }
         setAttributeInternal(TRANS_ACTIVE_2, value);
     }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FuncApprovals_VO.
     */
    public RowIterator getFuncApprovals_VO() {
        return (RowIterator)getAttributeInternal(FUNCAPPROVALS_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Level_Type_STATVO1.
     */
    public RowSet getLevel_Type_STATVO1() {
        return (RowSet)getAttributeInternal(LEVEL_TYPE_STATVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
