package fusion.um.model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 26 11:19:21 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuAccess_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MenuAccessId {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuAccessId();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setMenuAccessId((Number)value);
            }
        }
        ,
        UserRoleId {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getUserRoleId();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setUserRoleId((Number)value);
            }
        }
        ,
        SubMenuId {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getSubMenuId();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setSubMenuId((Number)value);
            }
        }
        ,
        MenuDisplay {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuDisplay();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setMenuDisplay((String)value);
            }
        }
        ,
        MenuControl {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuControl();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setMenuControl((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        RowID {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getRowID();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setRowID((oracle.jbo.domain.RowID)value);
            }
        }
        ,
        SubMenu {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getSubMenu();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setSubMenu((String)value);
            }
        }
        ,
        MenuName {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuName();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setMenuName((String)value);
            }
        }
        ,
        RoleName {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getRoleName();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setRoleName((String)value);
            }
        }
        ,
        Trans_MenuDisplay {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getTrans_MenuDisplay();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setTrans_MenuDisplay((Boolean)value);
            }
        }
        ,
        MenuSubMenu_ROVO1 {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuSubMenu_ROVO1();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UserRole_ROVO1 {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getUserRole_ROVO1();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MenuControl_STATVO1 {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getMenuControl_STATVO1();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AppRoles_ROVO1 {
            public Object get(MenuAccess_VORowImpl obj) {
                return obj.getAppRoles_ROVO1();
            }

            public void put(MenuAccess_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MenuAccess_VORowImpl object);

        public abstract void put(MenuAccess_VORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MENUACCESSID = AttributesEnum.MenuAccessId.index();
    public static final int USERROLEID = AttributesEnum.UserRoleId.index();
    public static final int SUBMENUID = AttributesEnum.SubMenuId.index();
    public static final int MENUDISPLAY = AttributesEnum.MenuDisplay.index();
    public static final int MENUCONTROL = AttributesEnum.MenuControl.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SUBMENU = AttributesEnum.SubMenu.index();
    public static final int MENUNAME = AttributesEnum.MenuName.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int TRANS_MENUDISPLAY = AttributesEnum.Trans_MenuDisplay.index();
    public static final int MENUSUBMENU_ROVO1 = AttributesEnum.MenuSubMenu_ROVO1.index();
    public static final int USERROLE_ROVO1 = AttributesEnum.UserRole_ROVO1.index();
    public static final int MENUCONTROL_STATVO1 = AttributesEnum.MenuControl_STATVO1.index();
    public static final int APPROLES_ROVO1 = AttributesEnum.AppRoles_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MenuAccess_VORowImpl() {
    }

    /**
     * Gets MenuAccess_EO entity object.
     * @return the MenuAccess_EO
     */
    public EntityImpl getMenuAccess_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for MENU_ACCESS_ID using the alias name MenuAccessId.
     * @return the MENU_ACCESS_ID
     */
    public Number getMenuAccessId() {
        return (Number)getAttributeInternal(MENUACCESSID);
    }

    /**
     * Sets <code>value</code> as attribute value for MENU_ACCESS_ID using the alias name MenuAccessId.
     * @param value value to set the MENU_ACCESS_ID
     */
    public void setMenuAccessId(Number value) {
        setAttributeInternal(MENUACCESSID, value);
    }

    /**
     * Gets the attribute value for USER_ROLE_ID using the alias name UserRoleId.
     * @return the USER_ROLE_ID
     */
    public Number getUserRoleId() {
        return (Number)getAttributeInternal(USERROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ROLE_ID using the alias name UserRoleId.
     * @param value value to set the USER_ROLE_ID
     */
    public void setUserRoleId(Number value) {
        setAttributeInternal(USERROLEID, value);
    }

    /**
     * Gets the attribute value for SUB_MENU_ID using the alias name SubMenuId.
     * @return the SUB_MENU_ID
     */
    public Number getSubMenuId() {
        return (Number)getAttributeInternal(SUBMENUID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_MENU_ID using the alias name SubMenuId.
     * @param value value to set the SUB_MENU_ID
     */
    public void setSubMenuId(Number value) {
        setAttributeInternal(SUBMENUID, value);
    }

    /**
     * Gets the attribute value for MENU_DISPLAY using the alias name MenuDisplay.
     * @return the MENU_DISPLAY
     */
    public String getMenuDisplay() {
        return (String)getAttributeInternal(MENUDISPLAY);
    }

    /**
     * Sets <code>value</code> as attribute value for MENU_DISPLAY using the alias name MenuDisplay.
     * @param value value to set the MENU_DISPLAY
     */
    public void setMenuDisplay(String value) {
        setAttributeInternal(MENUDISPLAY, value);
    }

    /**
     * Gets the attribute value for MENU_CONTROL using the alias name MenuControl.
     * @return the MENU_CONTROL
     */
    public String getMenuControl() {
        return (String)getAttributeInternal(MENUCONTROL);
    }

    /**
     * Sets <code>value</code> as attribute value for MENU_CONTROL using the alias name MenuControl.
     * @param value value to set the MENU_CONTROL
     */
    public void setMenuControl(String value) {
        setAttributeInternal(MENUCONTROL, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubMenu.
     * @return the SubMenu
     */
    public String getSubMenu() {
        return (String)getAttributeInternal(SUBMENU);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubMenu.
     * @param value value to set the  SubMenu
     */
    public void setSubMenu(String value) {
        setAttributeInternal(SUBMENU, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MenuName.
     * @return the MenuName
     */
    public String getMenuName() {
        return (String)getAttributeInternal(MENUNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MenuName.
     * @param value value to set the  MenuName
     */
    public void setMenuName(String value) {
        setAttributeInternal(MENUNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleName.
     * @return the RoleName
     */
    public String getRoleName() {
        return (String)getAttributeInternal(ROLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RoleName.
     * @param value value to set the  RoleName
     */
    public void setRoleName(String value) {
        setAttributeInternal(ROLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_MenuDisplay.
     * @return the Trans_MenuDisplay
     */
    public Boolean getTrans_MenuDisplay() {
        Boolean flag = false;
        if (this.getMenuDisplay() != null &&
            this.getMenuDisplay().equals("Y")) {
            flag = true;
            // System.err.println("flag"  + flag);
        } else {
            flag = false;
            //System.err.println("flag"  + flag);
        }
        return flag;
        //        return (Boolean) getAttributeInternal(TRANS_MENUDISPLAY);
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_MenuDisplay.
     * @param value value to set the  Trans_MenuDisplay
     */
    public void setTrans_MenuDisplay(Boolean value) {
        // System.err.println("value"  + setActiveYn(value));
        if (value != null && value == true) {
            setMenuDisplay("Y");
            //System.err.println("value"  + setActiveYn(value));
        } else {
            setMenuDisplay("N");
        }
        //        setAttributeInternal(TRANS_MENUDISPLAY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MenuSubMenu_ROVO1.
     */
    public RowSet getMenuSubMenu_ROVO1() {
        return (RowSet)getAttributeInternal(MENUSUBMENU_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UserRole_ROVO1.
     */
    public RowSet getUserRole_ROVO1() {
        return (RowSet)getAttributeInternal(USERROLE_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MenuControl_STATVO1.
     */
    public RowSet getMenuControl_STATVO1() {
        return (RowSet)getAttributeInternal(MENUCONTROL_STATVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AppRoles_ROVO1.
     */
    public RowSet getAppRoles_ROVO1() {
        return (RowSet)getAttributeInternal(APPROLES_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
