package fusion.um.model.ROVO;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 03 14:46:21 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Funtions_ROVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FuncId {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setFuncId((Number)value);
            }
        }
        ,
        FuncName {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getFuncName();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setFuncName((String)value);
            }
        }
        ,
        FuncShortCode {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getFuncShortCode();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setFuncShortCode((String)value);
            }
        }
        ,
        AutoNumberYn {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAutoNumberYn();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAutoNumberYn((String)value);
            }
        }
        ,
        Prefix {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getPrefix();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setPrefix((String)value);
            }
        }
        ,
        NextNumber {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getNextNumber();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setNextNumber((Number)value);
            }
        }
        ,
        PagePath {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getPagePath();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setPagePath((String)value);
            }
        }
        ,
        ActiveYn {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        InactiveOn {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getInactiveOn();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setInactiveOn((Date)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        FuncType {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getFuncType();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setFuncType((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        LookUp_ROVO1 {
            public Object get(Funtions_ROVORowImpl obj) {
                return obj.getLookUp_ROVO1();
            }

            public void put(Funtions_ROVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(Funtions_ROVORowImpl object);

        public abstract void put(Funtions_ROVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int FUNCNAME = AttributesEnum.FuncName.index();
    public static final int FUNCSHORTCODE = AttributesEnum.FuncShortCode.index();
    public static final int AUTONUMBERYN = AttributesEnum.AutoNumberYn.index();
    public static final int PREFIX = AttributesEnum.Prefix.index();
    public static final int NEXTNUMBER = AttributesEnum.NextNumber.index();
    public static final int PAGEPATH = AttributesEnum.PagePath.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int INACTIVEON = AttributesEnum.InactiveOn.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int FUNCTYPE = AttributesEnum.FuncType.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LOOKUP_ROVO1 = AttributesEnum.LookUp_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Funtions_ROVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute FuncId.
     * @return the FuncId
     */
    public Number getFuncId() {
        return (Number) getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FuncId.
     * @param value value to set the  FuncId
     */
    public void setFuncId(Number value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FuncName.
     * @return the FuncName
     */
    public String getFuncName() {
        return (String) getAttributeInternal(FUNCNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FuncName.
     * @param value value to set the  FuncName
     */
    public void setFuncName(String value) {
        setAttributeInternal(FUNCNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FuncShortCode.
     * @return the FuncShortCode
     */
    public String getFuncShortCode() {
        return (String) getAttributeInternal(FUNCSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FuncShortCode.
     * @param value value to set the  FuncShortCode
     */
    public void setFuncShortCode(String value) {
        setAttributeInternal(FUNCSHORTCODE, value.toUpperCase());
    }

    /**
     * Gets the attribute value for the calculated attribute AutoNumberYn.
     * @return the AutoNumberYn
     */
    public String getAutoNumberYn() {
        return (String) getAttributeInternal(AUTONUMBERYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AutoNumberYn.
     * @param value value to set the  AutoNumberYn
     */
    public void setAutoNumberYn(String value) {
        setAttributeInternal(AUTONUMBERYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Prefix.
     * @return the Prefix
     */
    public String getPrefix() {
        return (String) getAttributeInternal(PREFIX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Prefix.
     * @param value value to set the  Prefix
     */
    public void setPrefix(String value) {
        setAttributeInternal(PREFIX, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NextNumber.
     * @return the NextNumber
     */
    public Number getNextNumber() {
        return (Number) getAttributeInternal(NEXTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NextNumber.
     * @param value value to set the  NextNumber
     */
    public void setNextNumber(Number value) {
        setAttributeInternal(NEXTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PagePath.
     * @return the PagePath
     */
    public String getPagePath() {
        return (String) getAttributeInternal(PAGEPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PagePath.
     * @param value value to set the  PagePath
     */
    public void setPagePath(String value) {
        setAttributeInternal(PAGEPATH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActiveYn.
     * @return the ActiveYn
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActiveYn.
     * @param value value to set the  ActiveYn
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InactiveOn.
     * @return the InactiveOn
     */
    public Date getInactiveOn() {
        return (Date) getAttributeInternal(INACTIVEON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InactiveOn.
     * @param value value to set the  InactiveOn
     */
    public void setInactiveOn(Date value) {
        setAttributeInternal(INACTIVEON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AttributeCategory.
     * @return the AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AttributeCategory.
     * @param value value to set the  AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FuncType.
     * @return the FuncType
     */
    public String getFuncType() {
        return (String) getAttributeInternal(FUNCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FuncType.
     * @param value value to set the  FuncType
     */
    public void setFuncType(String value) {
        setAttributeInternal(FUNCTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1.
     * @param value value to set the  Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute2.
     * @param value value to set the  Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute3.
     * @param value value to set the  Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute4.
     * @param value value to set the  Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute5.
     * @param value value to set the  Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute6.
     * @param value value to set the  Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute7.
     * @param value value to set the  Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute8.
     * @param value value to set the  Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute9.
     * @param value value to set the  Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute10.
     * @param value value to set the  Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin.
     * @param value value to set the  LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookUp_ROVO1.
     */
    public RowSet getLookUp_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUP_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
