package fusion.um.model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 26 12:45:56 IST 2018
// ---------------------------------------------------------------------
public interface MenuAccess_AM extends ApplicationModule {
    void getResetData();

    void getCommitData();
}
