package fusion.um.model.PROGVO;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 21 22:41:52 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Segment3_PROGVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Seg3Key {
            public Object get(Segment3_PROGVORowImpl obj) {
                return obj.getSeg3Key();
            }

            public void put(Segment3_PROGVORowImpl obj, Object value) {
                obj.setSeg3Key((String)value);
            }
        }
        ,
        Seg3Value {
            public Object get(Segment3_PROGVORowImpl obj) {
                return obj.getSeg3Value();
            }

            public void put(Segment3_PROGVORowImpl obj, Object value) {
                obj.setSeg3Value((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(Segment3_PROGVORowImpl object);

        public abstract void put(Segment3_PROGVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SEG3KEY = AttributesEnum.Seg3Key.index();
    public static final int SEG3VALUE = AttributesEnum.Seg3Value.index();

    /**
     * This is the default constructor (do not remove).
     */
    public Segment3_PROGVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Seg3Key.
     * @return the Seg3Key
     */
    public String getSeg3Key() {
        return (String) getAttributeInternal(SEG3KEY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seg3Key.
     * @param value value to set the  Seg3Key
     */
    public void setSeg3Key(String value) {
        setAttributeInternal(SEG3KEY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Seg3Value.
     * @return the Seg3Value
     */
    public String getSeg3Value() {
        return (String) getAttributeInternal(SEG3VALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Seg3Value.
     * @param value value to set the  Seg3Value
     */
    public void setSeg3Value(String value) {
        setAttributeInternal(SEG3VALUE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
