package fusion.um.model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 20 16:15:31 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FuncApprovals_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FuncApprId {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getFuncApprId();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setFuncApprId((Number)value);
            }
        },
        ApprLevelId {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getApprLevelId();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setApprLevelId((Number)value);
            }
        },
        FuncId {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getFuncId();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setFuncId((Number)value);
            }
        },
        SeqNumber {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getSeqNumber();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setSeqNumber((Number)value);
            }
        },
        UserId {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getUserId();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setUserId((Number)value);
            }
        },
        ApprRole {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getApprRole();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setApprRole((String)value);
            }
        },
        ApprRoleDesc {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getApprRoleDesc();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setApprRoleDesc((String)value);
            }
        },
        ApprLimit {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getApprLimit();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setApprLimit((Number)value);
            }
        },
        ActiveYn {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        },
        AttributeCategory {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        },
        Attribute1 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        },
        Attribute2 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        },
        Attribute3 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        },
        Attribute4 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        },
        Attribute5 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        },
        Attribute6 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        },
        Attribute7 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        },
        Attribute8 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        },
        Attribute9 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        },
        Attribute10 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        },
        CreatedBy {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        },
        LastUpdatedBy {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdateDate {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        },
        LastUpdateLogin {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        },
        Trans_Active_1 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getTrans_Active_1();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setTrans_Active_1((Boolean)value);
            }
        },
        EmpId {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getEmpId();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setEmpId((Number)value);
            }
        },
        Trans_UserName {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getTrans_UserName();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setTrans_UserName((String)value);
            }
        },
        Trans_EmployeeName {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getTrans_EmployeeName();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setTrans_EmployeeName((String)value);
            }
        },
        FuncUserName_ROVO1 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getFuncUserName_ROVO1();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        FuncEmployeeName_ROVO1 {
            public Object get(FuncApprovals_VORowImpl obj) {
                return obj.getFuncEmployeeName_ROVO1();
            }

            public void put(FuncApprovals_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FuncApprovals_VORowImpl object);

        public abstract void put(FuncApprovals_VORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FUNCAPPRID = AttributesEnum.FuncApprId.index();
    public static final int APPRLEVELID = AttributesEnum.ApprLevelId.index();
    public static final int FUNCID = AttributesEnum.FuncId.index();
    public static final int SEQNUMBER = AttributesEnum.SeqNumber.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int APPRROLE = AttributesEnum.ApprRole.index();
    public static final int APPRROLEDESC = AttributesEnum.ApprRoleDesc.index();
    public static final int APPRLIMIT = AttributesEnum.ApprLimit.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int ATTRIBUTECATEGORY =
        AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN =
        AttributesEnum.LastUpdateLogin.index();
    public static final int TRANS_ACTIVE_1 =
        AttributesEnum.Trans_Active_1.index();
    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int TRANS_USERNAME =
        AttributesEnum.Trans_UserName.index();
    public static final int TRANS_EMPLOYEENAME =
        AttributesEnum.Trans_EmployeeName.index();
    public static final int FUNCUSERNAME_ROVO1 =
        AttributesEnum.FuncUserName_ROVO1.index();
    public static final int FUNCEMPLOYEENAME_ROVO1 =
        AttributesEnum.FuncEmployeeName_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FuncApprovals_VORowImpl() {
    }

    /**
     * Gets FuncApprovals_EO entity object.
     * @return the FuncApprovals_EO
     */
    public EntityImpl getFuncApprovals_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for FUNC_APPR_ID using the alias name FuncApprId.
     * @return the FUNC_APPR_ID
     */
    public Number getFuncApprId() {
        return (Number)getAttributeInternal(FUNCAPPRID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_APPR_ID using the alias name FuncApprId.
     * @param value value to set the FUNC_APPR_ID
     */
    public void setFuncApprId(Number value) {
        setAttributeInternal(FUNCAPPRID, value);
    }

    /**
     * Gets the attribute value for APPR_LEVEL_ID using the alias name ApprLevelId.
     * @return the APPR_LEVEL_ID
     */
    public Number getApprLevelId() {
        return (Number)getAttributeInternal(APPRLEVELID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_LEVEL_ID using the alias name ApprLevelId.
     * @param value value to set the APPR_LEVEL_ID
     */
    public void setApprLevelId(Number value) {
        setAttributeInternal(APPRLEVELID, value);
    }

    /**
     * Gets the attribute value for FUNC_ID using the alias name FuncId.
     * @return the FUNC_ID
     */
    public Number getFuncId() {
        return (Number)getAttributeInternal(FUNCID);
    }

    /**
     * Sets <code>value</code> as attribute value for FUNC_ID using the alias name FuncId.
     * @param value value to set the FUNC_ID
     */
    public void setFuncId(Number value) {
        setAttributeInternal(FUNCID, value);
    }

    /**
     * Gets the attribute value for SEQ_NUMBER using the alias name SeqNumber.
     * @return the SEQ_NUMBER
     */
    public Number getSeqNumber() {
        return (Number)getAttributeInternal(SEQNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SEQ_NUMBER using the alias name SeqNumber.
     * @param value value to set the SEQ_NUMBER
     */
    public void setSeqNumber(Number value) {
        setAttributeInternal(SEQNUMBER, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public Number getUserId() {
        return (Number)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for APPR_ROLE using the alias name ApprRole.
     * @return the APPR_ROLE
     */
    public String getApprRole() {
        return (String)getAttributeInternal(APPRROLE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_ROLE using the alias name ApprRole.
     * @param value value to set the APPR_ROLE
     */
    public void setApprRole(String value) {
        setAttributeInternal(APPRROLE, value);
    }

    /**
     * Gets the attribute value for APPR_ROLE_DESC using the alias name ApprRoleDesc.
     * @return the APPR_ROLE_DESC
     */
    public String getApprRoleDesc() {
        return (String)getAttributeInternal(APPRROLEDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_ROLE_DESC using the alias name ApprRoleDesc.
     * @param value value to set the APPR_ROLE_DESC
     */
    public void setApprRoleDesc(String value) {
        setAttributeInternal(APPRROLEDESC, value);
    }

    /**
     * Gets the attribute value for EMP_ID using the alias name EmpId.
     * @return the EMP_ID
     */
    public Number getEmpId() {
        return (Number)getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ID using the alias name EmpId.
     * @param value value to set the EMP_ID
     */
    public void setEmpId(Number value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_UserName.
     * @return the Trans_UserName
     */
    public String getTrans_UserName() {
        return (String)getAttributeInternal(TRANS_USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_UserName.
     * @param value value to set the  Trans_UserName
     */
    public void setTrans_UserName(String value) {
        setAttributeInternal(TRANS_USERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_EmployeeName.
     * @return the Trans_EmployeeName
     */
    public String getTrans_EmployeeName() {
        return (String)getAttributeInternal(TRANS_EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_EmployeeName.
     * @param value value to set the  Trans_EmployeeName
     */
    public void setTrans_EmployeeName(String value) {
        setAttributeInternal(TRANS_EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for APPR_LIMIT using the alias name ApprLimit.
     * @return the APPR_LIMIT
     */
    public Number getApprLimit() {
        return (Number)getAttributeInternal(APPRLIMIT);
    }

    /**
     * Sets <code>value</code> as attribute value for APPR_LIMIT using the alias name ApprLimit.
     * @param value value to set the APPR_LIMIT
     */
    public void setApprLimit(Number value) {
        setAttributeInternal(APPRLIMIT, value);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String)getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Active_1.
     * @return the Trans_Active_1
     */
    public Boolean getTrans_Active_1() {
        Boolean flag = false;
        if (this.getActiveYn() != null && this.getActiveYn().equals("Y")) {
            flag = true;
            //            System.err.println("flag"  + flag);
        } else {
            flag = false;
            //            System.err.println("flag"  + flag);
        }
        return flag;
        //          return (Boolean) getAttributeInternal(TRANS_ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Active_1.
     * @param value value to set the  Trans_Active_1
     */
    public void setTrans_Active_1(Boolean value) {
        if (value) {
            setActiveYn("Y");
        } else {
            setActiveYn("N");
        }
        setAttributeInternal(TRANS_ACTIVE_1, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> FuncUserName_ROVO1.
     */
    public RowSet getFuncUserName_ROVO1() {
        return (RowSet)getAttributeInternal(FUNCUSERNAME_ROVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> FuncEmployeeName_ROVO1.
     */
    public RowSet getFuncEmployeeName_ROVO1() {
        return (RowSet)getAttributeInternal(FUNCEMPLOYEENAME_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
