package fusion.um.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 29 11:33:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValues_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LookupValues_VOImpl() {
    }
}
