package fusion.um.model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 21 15:29:05 IST 2019
// ---------------------------------------------------------------------
public interface CheckUserAppModule extends ApplicationModule {
    String CheckUserName(String jwt);
}
