package fusion.um.model.VO;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 29 11:33:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValues_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LookupValueId {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupValueId();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupValueId((Number)value);
            }
        }
        ,
        LookupTypeId {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupTypeId();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupTypeId((Number)value);
            }
        }
        ,
        LookupValueName {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupValueName();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupValueName((String)value);
            }
        }
        ,
        LookupValueNameDisp {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupValueNameDisp();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupValueNameDisp((String)value);
            }
        }
        ,
        LookupValueNameDispTl {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupValueNameDispTl();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupValueNameDispTl((String)value);
            }
        }
        ,
        AccessLevel {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getAccessLevel();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setAccessLevel((String)value);
            }
        }
        ,
        LookupAddlValue {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupAddlValue();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLookupAddlValue((String)value);
            }
        }
        ,
        ActiveYn {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        ParentValueId {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getParentValueId();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setParentValueId((Number)value);
            }
        }
        ,
        RowID {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getRowID();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ,
        Trans_Active {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getTrans_Active();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setTrans_Active((Boolean)value);
            }
        }
        ,
        Trans_Parent_id {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getTrans_Parent_id();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setTrans_Parent_id((Number)value);
            }
        }
        ,
        LookupTypes_VO {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupTypes_VO();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupAccessLevel_STATVO1 {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupAccessLevel_STATVO1();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LookupParentValue_ROVO1 {
            public Object get(LookupValues_VORowImpl obj) {
                return obj.getLookupParentValue_ROVO1();
            }

            public void put(LookupValues_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LookupValues_VORowImpl object);

        public abstract void put(LookupValues_VORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LOOKUPVALUEID = AttributesEnum.LookupValueId.index();
    public static final int LOOKUPTYPEID = AttributesEnum.LookupTypeId.index();
    public static final int LOOKUPVALUENAME = AttributesEnum.LookupValueName.index();
    public static final int LOOKUPVALUENAMEDISP = AttributesEnum.LookupValueNameDisp.index();
    public static final int LOOKUPVALUENAMEDISPTL = AttributesEnum.LookupValueNameDispTl.index();
    public static final int ACCESSLEVEL = AttributesEnum.AccessLevel.index();
    public static final int LOOKUPADDLVALUE = AttributesEnum.LookupAddlValue.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int PARENTVALUEID = AttributesEnum.ParentValueId.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int TRANS_ACTIVE = AttributesEnum.Trans_Active.index();
    public static final int TRANS_PARENT_ID = AttributesEnum.Trans_Parent_id.index();
    public static final int LOOKUPTYPES_VO = AttributesEnum.LookupTypes_VO.index();
    public static final int LOOKUPACCESSLEVEL_STATVO1 = AttributesEnum.LookupAccessLevel_STATVO1.index();
    public static final int LOOKUPPARENTVALUE_ROVO1 = AttributesEnum.LookupParentValue_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookupValues_VORowImpl() {
    }

    /**
     * Gets LookupValues_EO entity object.
     * @return the LookupValues_EO
     */
    public EntityImpl getLookupValues_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LOOKUP_VALUE_ID using the alias name LookupValueId.
     * @return the LOOKUP_VALUE_ID
     */
    public Number getLookupValueId() {
        return (Number)getAttributeInternal(LOOKUPVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_VALUE_ID using the alias name LookupValueId.
     * @param value value to set the LOOKUP_VALUE_ID
     */
    public void setLookupValueId(Number value) {
        setAttributeInternal(LOOKUPVALUEID, value);
    }

    /**
     * Gets the attribute value for LOOKUP_TYPE_ID using the alias name LookupTypeId.
     * @return the LOOKUP_TYPE_ID
     */
    public Number getLookupTypeId() {
        return (Number)getAttributeInternal(LOOKUPTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_TYPE_ID using the alias name LookupTypeId.
     * @param value value to set the LOOKUP_TYPE_ID
     */
    public void setLookupTypeId(Number value) {
        setAttributeInternal(LOOKUPTYPEID, value);
    }

    /**
     * Gets the attribute value for LOOKUP_VALUE_NAME using the alias name LookupValueName.
     * @return the LOOKUP_VALUE_NAME
     */
    public String getLookupValueName() {
        return (String)getAttributeInternal(LOOKUPVALUENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_VALUE_NAME using the alias name LookupValueName.
     * @param value value to set the LOOKUP_VALUE_NAME
     */
    public void setLookupValueName(String value) {
        setAttributeInternal(LOOKUPVALUENAME, value);
    }

    /**
     * Gets the attribute value for LOOKUP_VALUE_NAME_DISP using the alias name LookupValueNameDisp.
     * @return the LOOKUP_VALUE_NAME_DISP
     */
    public String getLookupValueNameDisp() {
        return (String)getAttributeInternal(LOOKUPVALUENAMEDISP);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_VALUE_NAME_DISP using the alias name LookupValueNameDisp.
     * @param value value to set the LOOKUP_VALUE_NAME_DISP
     */
    public void setLookupValueNameDisp(String value) {
        setAttributeInternal(LOOKUPVALUENAMEDISP, value);
    }

    /**
     * Gets the attribute value for LOOKUP_VALUE_NAME_DISP_TL using the alias name LookupValueNameDispTl.
     * @return the LOOKUP_VALUE_NAME_DISP_TL
     */
    public String getLookupValueNameDispTl() {
        return (String)getAttributeInternal(LOOKUPVALUENAMEDISPTL);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_VALUE_NAME_DISP_TL using the alias name LookupValueNameDispTl.
     * @param value value to set the LOOKUP_VALUE_NAME_DISP_TL
     */
    public void setLookupValueNameDispTl(String value) {
        setAttributeInternal(LOOKUPVALUENAMEDISPTL, value);
    }

    /**
     * Gets the attribute value for ACCESS_LEVEL using the alias name AccessLevel.
     * @return the ACCESS_LEVEL
     */
    public String getAccessLevel() {
        return (String)getAttributeInternal(ACCESSLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESS_LEVEL using the alias name AccessLevel.
     * @param value value to set the ACCESS_LEVEL
     */
    public void setAccessLevel(String value) {
        setAttributeInternal(ACCESSLEVEL, value);
    }

    /**
     * Gets the attribute value for LOOKUP_ADDL_VALUE using the alias name LookupAddlValue.
     * @return the LOOKUP_ADDL_VALUE
     */
    public String getLookupAddlValue() {
        return (String)getAttributeInternal(LOOKUPADDLVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOOKUP_ADDL_VALUE using the alias name LookupAddlValue.
     * @param value value to set the LOOKUP_ADDL_VALUE
     */
    public void setLookupAddlValue(String value) {
        setAttributeInternal(LOOKUPADDLVALUE, value);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String)getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for PARENT_VALUE_ID using the alias name ParentValueId.
     * @return the PARENT_VALUE_ID
     */
    public Number getParentValueId() {
        return (Number)getAttributeInternal(PARENTVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARENT_VALUE_ID using the alias name ParentValueId.
     * @param value value to set the PARENT_VALUE_ID
     */
    public void setParentValueId(Number value) {
        setAttributeInternal(PARENTVALUEID, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Active.
     * @return the Trans_Active
     */
    public Boolean getTrans_Active() {
        Boolean flag = false;
        if (this.getActiveYn() != null && this.getActiveYn().equals("Y")) {
            flag = true;
            //            System.err.println("flag"  + flag);
        } else {
            flag = false;
            //            System.err.println("flag"  + flag);
        }
        return flag;
        //        return (Boolean) getAttributeInternal(TRANS_ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Active.
     * @param value value to set the  Trans_Active
     */
    public void setTrans_Active(Boolean value) {
        if (value) {
            setActiveYn("Y");
        } else {
            setActiveYn("N");
        }
        setAttributeInternal(TRANS_ACTIVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Parent_id.
     * @return the Trans_Parent_id
     */
    public Number getTrans_Parent_id() {
        return (Number) getAttributeInternal(TRANS_PARENT_ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Parent_id.
     * @param value value to set the  Trans_Parent_id
     */
    public void setTrans_Parent_id(Number value) {
        setAttributeInternal(TRANS_PARENT_ID, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link LookupTypes_VO.
     */
    public Row getLookupTypes_VO() {
        return (Row)getAttributeInternal(LOOKUPTYPES_VO);
    }

    /**
     * Sets the master-detail link LookupTypes_VO between this object and <code>value</code>.
     */
    public void setLookupTypes_VO(Row value) {
        setAttributeInternal(LOOKUPTYPES_VO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupAccessLevel_STATVO1.
     */
    public RowSet getLookupAccessLevel_STATVO1() {
        return (RowSet)getAttributeInternal(LOOKUPACCESSLEVEL_STATVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LookupParentValue_ROVO1.
     */
    public RowSet getLookupParentValue_ROVO1() {
        return (RowSet)getAttributeInternal(LOOKUPPARENTVALUE_ROVO1);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
