package fusion.um.model.AM;

import fusion.um.model.AM.common.CheckUserAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
import java.util.HashMap;
import java.util.Map;
import com.octetstring.vde.util.Base64;
import oracle.adf.share.ADFContext;
import oracle.adf.share.logging.ADFLogger;
import org.json.JSONException;
import org.json.JSONObject;
import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 21 15:01:20 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CheckUserAppModuleImpl extends ApplicationModuleImpl implements CheckUserAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public CheckUserAppModuleImpl() {
    }

    /**
     * Container's getter for checkUserROVO1.
     * @return checkUserROVO1
     */
    public ViewObjectImpl getcheckUserROVO1() {
        return (ViewObjectImpl)findViewObject("checkUserROVO1");
    }
    
    public String CheckUserName(String jwt1){
        String jwt=ADFContext.getCurrent().getPageFlowScope().get("tokens")==null?null:
                   ADFContext.getCurrent().getPageFlowScope().get("tokens").toString();
        System.err.println("TOKEN==>"+ADFContext.getCurrent().getPageFlowScope().get("tokens"));
        String pageRedirect = "invalid";
//        #{pageFlowScope.tokens}
// Sample Token
//eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1dCI6IlRBc0pMVXY0MFVuaWRJclVrRGFwRzhFXzlLOCJ9.eyJleHAiOjE0ODM1MzA3NzEsImlzcyI6Ind3dy5vcmFjbGUuY29tIiwicHJuIjoiYXBpIiwiaWF0IjoxNDgzNTE2MzcxfQ.ALvDilyGj-VQUmRQnUc7L1tz895bxjiSfPetczwqbUhMTmBIIoyJd9tKFQTnYPg8esUiiym8RnXRisFXcWmdmcoYAg3bbhqQ877KBDdXg6_CAk5h4OSHG8jgXhWFSJsE-
        String userRole = null;
        if (jwt != null) {
        System.err.println("==>in");
            String inputEncodedText = jwt;
                //ADFContext.getCurrent().getPageFlowScope().get("tokens").toString();
            try {
                String[] xIn = inputEncodedText.split("\\.");
                byte b[] = Base64.decode(xIn[1]);
                String tempPass = new String(b);
                int chkOccurance = tempPass.lastIndexOf("}");
                if (chkOccurance < 1) {
                    tempPass += "}";
                }
                JSONObject jo;

                jo = new JSONObject(tempPass);
//                sessionMap.put("userName", jo.getString("prn"));
                //TODO commenting hard coded values since PROFILE_VALUED coming from lookup data
//                System.err.println("User Name==" + sessionMap.get("userName"));
                System.err.println("PRN==>"+jo.getString("prn"));
                ViewObject getUserDetailsVO = this.getcheckUserROVO1().getViewObject();
                getUserDetailsVO .setNamedWhereClauseParam("USER_NAME", jo.getString("prn"));
                getUserDetailsVO .executeQuery();
               System.err.println("COUNT-->"+getUserDetailsVO.getEstimatedRowCount());
                if (getUserDetailsVO .getEstimatedRowCount() > 0) {
                    Row re = getUserDetailsVO .first();
                    if (re.getAttribute("LookupValueName") != null) {
                        userRole = re.getAttribute("LookupValueName").toString();
                      
                    }
                    if(userRole.equalsIgnoreCase("SALES_ADMIN")){
                        pageRedirect = "validUser"; 
                        ADFContext.getCurrent().getPageFlowScope().put("val","validUser");
                    }else{
                        pageRedirect = "invalidUser";
                        ADFContext.getCurrent().getPageFlowScope().put("val","invalidUser");
                    }
                } else {
                    pageRedirect = "invalidUser";
                    ADFContext.getCurrent().getPageFlowScope().put("val","invalidUser");
                }
            } catch (Exception e) {
                
            }
        } else {
            pageRedirect = "invalidUser";  
            ADFContext.getCurrent().getPageFlowScope().put("val","invalidUser");
        }
        return pageRedirect;    
    }
    
    
}
