package fusion.um.model.AM;

import fusion.um.model.AM.common.MenuAccess_AM;
import fusion.um.model.VO.MenuAccess_VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 26 12:44:28 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MenuAccess_AMImpl extends ApplicationModuleImpl implements MenuAccess_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public MenuAccess_AMImpl() {
    }

    /**
     * Container's getter for UserRole_ROVO1.
     * @return UserRole_ROVO1
     */
    public ViewObjectImpl getUserRole_ROVO1() {
        return (ViewObjectImpl)findViewObject("UserRole_ROVO1");
    }

    /**
     * Container's getter for MenuAccess_VO1.
     * @return MenuAccess_VO1
     */
    public MenuAccess_VOImpl getMenuAccess_VO1() {
        return (MenuAccess_VOImpl)findViewObject("MenuAccess_VO1");
    }

    /**
     * Container's getter for SubMenu_ROVO1.
     * @return SubMenu_ROVO1
     */
    public ViewObjectImpl getSubMenu_ROVO1() {
        return (ViewObjectImpl)findViewObject("SubMenu_ROVO1");
    }

    public void getCommitData() {
        this.getDBTransaction().commit();
        System.err.println("===1===");
    }

    public void getResetData() {
        this.getMenuAccess_VO1().executeEmptyRowSet();
        System.err.println("===15===");
    }
}
