package fusion.um.model.ROVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 03 14:46:22 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Funtions_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Funtions_ROVOImpl() {
    }

    /**
     * Returns the variable value for BV_NAME.
     * @return variable value for BV_NAME
     */
    public String getBV_NAME() {
        return (String)ensureVariableManager().getVariableValue("BV_NAME");
    }

    /**
     * Sets <code>value</code> for variable BV_NAME.
     * @param value value to bind as BV_NAME
     */
    public void setBV_NAME(String value) {
        ensureVariableManager().setVariableValue("BV_NAME", value);
    }

    /**
     * Returns the variable value for BV_CODE.
     * @return variable value for BV_CODE
     */
    public String getBV_CODE() {
        return (String)ensureVariableManager().getVariableValue("BV_CODE");
    }

    /**
     * Sets <code>value</code> for variable BV_CODE.
     * @param value value to bind as BV_CODE
     */
    public void setBV_CODE(String value) {
        ensureVariableManager().setVariableValue("BV_CODE", value);
    }
}
