package fusion.um.model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 25 18:24:13 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DataGroupDetail_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DataDetailId {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getDataDetailId();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setDataDetailId((Number)value);
            }
        }
        ,
        DataGroupId {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getDataGroupId();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setDataGroupId((Number)value);
            }
        }
        ,
        DcombId {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getDcombId();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setDcombId((Number)value);
            }
        }
        ,
        ActiveYn {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getActiveYn();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setActiveYn((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        Trans_Active {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getTrans_Active();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setTrans_Active((Boolean)value);
            }
        }
        ,
        SegmentComb_ROVO1 {
            public Object get(DataGroupDetail_VORowImpl obj) {
                return obj.getSegmentComb_ROVO1();
            }

            public void put(DataGroupDetail_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DataGroupDetail_VORowImpl object);

        public abstract void put(DataGroupDetail_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DATADETAILID = AttributesEnum.DataDetailId.index();
    public static final int DATAGROUPID = AttributesEnum.DataGroupId.index();
    public static final int DCOMBID = AttributesEnum.DcombId.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int TRANS_ACTIVE = AttributesEnum.Trans_Active.index();
    public static final int SEGMENTCOMB_ROVO1 = AttributesEnum.SegmentComb_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DataGroupDetail_VORowImpl() {
    }

    /**
     * Gets DataGroupDetail_EO entity object.
     * @return the DataGroupDetail_EO
     */
    public EntityImpl getDataGroupDetail_EO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DATA_DETAIL_ID using the alias name DataDetailId.
     * @return the DATA_DETAIL_ID
     */
    public Number getDataDetailId() {
        return (Number) getAttributeInternal(DATADETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_DETAIL_ID using the alias name DataDetailId.
     * @param value value to set the DATA_DETAIL_ID
     */
    public void setDataDetailId(Number value) {
        setAttributeInternal(DATADETAILID, value);
    }

    /**
     * Gets the attribute value for DATA_GROUP_ID using the alias name DataGroupId.
     * @return the DATA_GROUP_ID
     */
    public Number getDataGroupId() {
        return (Number) getAttributeInternal(DATAGROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_GROUP_ID using the alias name DataGroupId.
     * @param value value to set the DATA_GROUP_ID
     */
    public void setDataGroupId(Number value) {
        setAttributeInternal(DATAGROUPID, value);
    }

    /**
     * Gets the attribute value for DCOMB_ID using the alias name DcombId.
     * @return the DCOMB_ID
     */
    public Number getDcombId() {
        return (Number) getAttributeInternal(DCOMBID);
    }

    /**
     * Sets <code>value</code> as attribute value for DCOMB_ID using the alias name DcombId.
     * @param value value to set the DCOMB_ID
     */
    public void setDcombId(Number value) {
        setAttributeInternal(DCOMBID, value);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Active.
     * @return the Trans_Active
     */
     public Boolean getTrans_Active() {
         Boolean flag = false;
         if (this.getActiveYn() != null && this.getActiveYn().equals("Y")) {
             flag = true;
     //             System.err.println("flag"  + flag);
         } else {
             flag = false;
     //             System.err.println("flag"  + flag);
         }
         return flag;
     //          return (Boolean) getAttributeInternal(TRANS_ACTIVE);
     }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Active.
     * @param value value to set the  Trans_Active
     */
     public void setTrans_Active(Boolean value) {
         if (value) {
             setActiveYn("Y");
         } else {
             setActiveYn("N");
         }
         setAttributeInternal(TRANS_ACTIVE, value);
     }

    /**
     * Gets the view accessor <code>RowSet</code> SegmentComb_ROVO1.
     */
    public RowSet getSegmentComb_ROVO1() {
        return (RowSet)getAttributeInternal(SEGMENTCOMB_ROVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
